# Generated by Django 4.2.1 on 2023-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_alter_guide_summarizeddescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='summarizedDescription',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
