# Generated by Django 4.2.1 on 2023-05-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HuntingGrounds',
        ),
    ]
