# Generated by Django 4.2.1 on 2023-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0002_delete_huntinggrounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishes',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
