# Generated by Django 4.2.1 on 2023-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0004_alter_fishes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fishes',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
