# Generated by Django 4.2.1 on 2023-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0005_category_slug_alter_fishes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishes',
            name='image',
            field=models.ImageField(upload_to='fishes'),
        ),
    ]
