# Generated by Django 4.2.1 on 2023-05-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0006_alter_fishes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fishes/'),
        ),
    ]
