# Generated by Django 4.2.1 on 2023-05-21 11:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0007_alter_fishes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishes',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
