# Generated by Django 4.2.1 on 2023-05-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0008_alter_fishes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fishes.category'),
        ),
    ]
