# Generated by Django 4.2.1 on 2023-05-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntingGrounds', '0005_remove_grounds_fishes'),
        ('fishes', '0009_fishes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishes',
            name='grounds',
            field=models.ManyToManyField(to='huntingGrounds.grounds'),
        ),
    ]
