# Generated by Django 4.2.1 on 2023-05-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0012_fishes_summarizedescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishes',
            old_name='summarizeDescription',
            new_name='summarizedDescription',
        ),
    ]
