# Generated by Django 4.2.1 on 2023-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0014_alter_fishes_summarizeddescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishes',
            name='summarizedDescription',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
