# Generated by Django 4.2.1 on 2023-06-09 07:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0015_alter_fishes_summarizeddescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishes',
            name='tactic',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
