# Generated by Django 4.2.1 on 2023-05-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntingGrounds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HuntingGrounds',
            new_name='Grounds',
        ),
    ]
