# Generated by Django 4.2.1 on 2023-05-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntingGrounds', '0004_grounds_fishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grounds',
            name='fishes',
        ),
    ]
