# Generated by Django 4.2.1 on 2023-05-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0011_remove_fishes_grounds'),
        ('huntingGrounds', '0005_remove_grounds_fishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grounds',
            name='fishes',
            field=models.ManyToManyField(to='fishes.fishes'),
        ),
    ]
