# Generated by Django 4.2.1 on 2023-05-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntingGrounds', '0006_grounds_fishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grounds',
            name='summarizedDescription',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
